//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenNhutDuy_2122110447.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyKhoGiaoHangEntities3 : DbContext
    {
        public QuanLyKhoGiaoHangEntities3()
            : base("name=QuanLyKhoGiaoHangEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<GiaoHang> GiaoHangs { get; set; }
        public virtual DbSet<LoiNhanVien> LoiNhanViens { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<QuanLyVatTu> QuanLyVatTus { get; set; }
        public virtual DbSet<LichSuBanGiaoVatTu> LichSuBanGiaoVatTus { get; set; }
        public virtual DbSet<LichSuGiaoHang> LichSuGiaoHangs { get; set; }
        public virtual DbSet<LichSuPhanPhoi> LichSuPhanPhois { get; set; }
    }
}
